In [ ]:
import torch

# Tensors

In [ ]:
t1 = torch.tensor(4.)
t1

# we need to pass 4. instead of 4 because AutoGrad (gradient calculation) works
# with float values and not integer

# we are converting everything to tensors because in GPU we can make use of
# around 4000 cores for faster computation

tensor(4.)

In [ ]:
type(t1)

torch.Tensor

In [ ]:
t1.dtype

torch.float32

# Vectors

In [ ]:
t2 = torch.tensor([1.,2.,3.,4.])

In [ ]:
t2

tensor([1., 2., 3., 4.])

In [ ]:
t2.dtype

torch.float32

# Matrix

In [ ]:
t3 = torch.tensor(
    [
      [4.,5,6,9],
      [10,11,12,13]
    ]
)

# Tensors are like arrays. Can store only homogeneous data

In [ ]:
t3

tensor([[ 4.,  5.,  6.,  9.],
        [10., 11., 12., 13.]])

In [ ]:
t3.dtype

torch.float32

In [ ]:
# 3-D Tensor

t4 = torch.tensor(
    [
     [
      [11.,12,13],
      [14,15,16],
     ],
     [
      [22.,23,24],
      [25,26,27],
     ]
    ]
)

In [ ]:
t4

tensor([[[11., 12., 13.],
         [14., 15., 16.]],

        [[22., 23., 24.],
         [25., 26., 27.]]])

In [ ]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [ ]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [ ]:
print(t3)
t3.shape

tensor([[ 4.,  5.,  6.,  9.],
        [10., 11., 12., 13.]])


torch.Size([2, 4])

In [ ]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [14., 15., 16.]],

        [[22., 23., 24.],
         [25., 26., 27.]]])


torch.Size([2, 2, 3])

# Tensors Operations

In [ ]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

# PyTorch calculates gradients automatically and so we specify the 
# requires_grad=True for those parameters where gradient 
# calculation is required. So during training PyTorch will know that 
# only w and b need to be trained and not x.

In [ ]:
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
y.backward()

In [ ]:
print("dy/dx: ", x.grad)
print("dy/dw: ", w.grad)
print("dy/db: ", b.grad)

dy/dx:  None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)


In [ ]:
t5 = torch.full((3,2), 23)

# similar ro numpy.zeros and numpy.ones
# set all elements to same value for given shape

In [ ]:
t5

tensor([[23, 23],
        [23, 23],
        [23, 23]])

In [ ]:
t6 = torch.full((5,2), 99)

In [ ]:
t6

tensor([[99, 99],
        [99, 99],
        [99, 99],
        [99, 99],
        [99, 99]])

In [ ]:
t7 = torch.cat((t5,t6))

In [ ]:
t7

tensor([[23, 23],
        [23, 23],
        [23, 23],
        [99, 99],
        [99, 99],
        [99, 99],
        [99, 99],
        [99, 99]])

In [ ]:
t8 = torch.sin(t5)

In [ ]:
t8

tensor([[-0.8462, -0.8462],
        [-0.8462, -0.8462],
        [-0.8462, -0.8462]])

In [ ]:
t9 = t7.reshape(2,8)

In [ ]:
t9

tensor([[23, 23, 23, 23, 23, 23, 99, 99],
        [99, 99, 99, 99, 99, 99, 99, 99]])

# Interoperability with NumPy

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2], [7,8]])

In [ ]:
a

array([[1, 2],
       [7, 8]])

In [ ]:
# convert numpy array to tensor
y = torch.from_numpy(a)

In [ ]:
y

tensor([[1, 2],
        [7, 8]])

In [ ]:
# convert tensor to numpy array
z = y.numpy()

In [ ]:
z

array([[1, 2],
       [7, 8]])