In [1]:
import numpy as np

In [2]:
import array

In [3]:
np.random.rand(3,4)

array([[0.00747503, 0.7762989 , 0.18022816, 0.96280343],
       [0.92925377, 0.12494427, 0.92796955, 0.61822975],
       [0.15220497, 0.81254209, 0.10833161, 0.8573543 ]])

In [4]:
arr = np.random.randint(1,50,(3,3))

In [5]:
arr

array([[ 2, 16, 21],
       [17,  9,  6],
       [45, 27, 37]])

In [6]:
arr[0][2]

21

In [7]:
arr[0][0:]

array([ 2, 16, 21])

In [13]:
arr[1:3][1:]

array([[45, 27, 37]])

In [18]:
np.random.seed(30)
np.random.rand(2,4)

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073],
       [0.96260781, 0.34666184, 0.99175099, 0.2350579 ]])